### ISSUE TITLE
Feature request: use env variable for Test mode

### ISSUE THREAD

**Issue by bartdigitalpulse** [craftcms/commerce-multisafepay#16]
### Description

When testing locally I change the setting back to "test mode". This causes a yaml file change.  Would be great if there was an env setting to enable / disable this so the yaml file wouldn't get changed.

### Additional info

- Craft version: Craft Pro 3.7.51

**Comment by nfourtythree** [comment]
HI @bartdigitalpulse 

Thank you for your message.

Environment variable support for all gateway settings was added in version 4 of the plugin.

Thanks!
